apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-selvbetjening-opptjening-frontend
  namespace: pensjonselvbetjening
  labels:
    team: pensjonselvbetjening
  annotations:
    nais.io/run-as-user: "101" # nginx
    nais.io/read-only-file-system: "false" # need write /etc/nginx/conf.d
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
spec:
  image: {{ image }}
  ingresses:
    - https://www-gcp.intern.dev.nav.no/pensjon/opptjening
    - https://www-gcp.ansatt.dev.nav.no/pensjon/opptjening
  port: 8080
  replicas:
    min: 2
    max: 2
  liveness:
    path: /internal/alive
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  readiness:
    path: /internal/ready
    initialDelay: 30
    timeout: 1
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/ping
        - /internal/selftest
        - /pensjon/opptjening/api/status
        - /pensjon/opptjening/static/*
  accessPolicy:
    outbound:
      rules:
        - application: pensjon-selvbetjening-opptjening-backend
      external:
        - host: www-gcp.dev.nav.no
  env:
    - name: "OPPTJENING_BACKEND"
      value: "http://pensjon-selvbetjening-opptjening-backend"
