apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-selvbetjening-opptjening-frontend
  namespace: pensjonselvbetjening
  labels:
    team: pensjonselvbetjening
  annotations:
    nais.io/run-as-user: "101" # nginx
    nais.io/read-only-file-system: "false" # need write /etc/nginx/conf.d
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  image: {{ image_prod_fss }}
  port: 8080
  replicas:
    min: 2
    max: 2
  liveness:
    path: "/api/internal/isAlive"
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  readiness:
    path: "/api/internal/isReady"
    initialDelay: 30
    timeout: 1
  ingresses:
    - "https://pensjon-selvbetjening-opptjening-frontend.nais.adeo.no"
  env:
    - name: "OPPTJENING_BACKEND"
      value: "https://pensjon-selvbetjening-opptjening-backend.nais.adeo.no"
