apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-veiledning-opptjening-frontend
  namespace: pensjonselvbetjening
  labels:
    team: pensjonselvbetjening
  annotations:
    nais.io/run-as-user: "101" # nginx
    nais.io/read-only-file-system: "false" # need write /etc/nginx/conf.d
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  image: "{{ image }}"
  ingresses:
    - https://pensjon-veiledning-opptjening-frontend.intern.nav.no
  port: 8080
  replicas:
    min: 2
    max: 4
  liveness:
    path: /internal/alive
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  readiness:
    path: /internal/ready
    initialDelay: 30
    timeout: 1
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "7845a796-1516-4d14-b500-fd65c001f35c" # 0000-GA-PENSJON_BRUKERHJELPA
          - id: "70ef8e7f-7456-4298-95e0-b13c0ef2422b" # 0000-GA-Pensjon_Okonomi
          - id: "0af3955f-df85-4eb0-b5b2-45bf2c8aeb9e" # 0000-GA-PENSJON_SAKSBEHANDLER
          - id: "959ead5b-99b5-466b-a0ff-5fdbc687517b" # 0000-GA-Pensjon_VEILEDER
          - id: "e750ceb5-b70b-4d94-b4fa-9d22467b786b" # 0000-GA-Egne_ansatte
          - id: "9ec6487d-f37a-4aad-a027-cd221c1ac32b" # 0000-GA-Fortrolig_Adresse
          - id: "ad7b87a6-9180-467c-affc-20a566b0fec0" # 0000-GA-Strengt_Fortrolig_Adresse
        extra:
          - NAVident
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/ping
        - /internal/selftest
        - /pensjon/opptjening/api/status
        - /pensjon/opptjening/static/**
        - /pensjon/opptjening/manifest.json
  accessPolicy:
    outbound:
      rules:
        - application: pensjon-selvbetjening-opptjening-backend
      external:
        - host: pensjon-veiledning-opptjening-frontend.intern.nav.no
  env:
    - name: "OPPTJENING_BACKEND"
      value: "http://pensjon-selvbetjening-opptjening-backend"
  envFrom:
    - secret: opptjening-frontend-unleash-api-token
