== Starte app på localhost
Bruk `npm run dev` for å kjøre appen i utviklingsmodus
Åpne http://localhost:3000/pensjon/opptjening for å se den i nettleser.
App'en kjører da opp en lokal JSON-server med noe deafult data.

Mock data ligger i mappa "dev" på rotnivå og app'en vil kjøre opp default med `mock.json`.
Ønsker man å starte opp med med andre testdata kan man angi filen som parameter (antar at filen ligger under i mappa "dev"):
`npm run dev --  <filnavn>`.

Vi har følgende testdata tilgjengelig:
|===
| Fil | Beskrivelse

| mock.json | Default. Bruker født etter 1962
| mock_usergroup1 | Bruker født før 1954
| mock_usergroup2 | Bruker født mellom 1954 og 1962
| mock_usergroup2 | Bruker født mellom 1954 og 1962
| mock_usergroup2 | Bruker født mellom 1954 og 1962
| mock_usergroup2 | Bruker født mellom 1954 og 1962
| mock_blandetuttak.json | Bruker med ulike grader av uttak
| mock_fulluttak.json | Bruker med 100 % uttak
| mock_gradertuttak.json | Bruker med gradert uttak
| mock_omsorgsopptjeningmindreenninntekt.json | Bruker som har omsorgsopptjening mindre enn inntekt et år
|===

== Tilgjengelige script

|===
| Script | Beskrivelse

| npm run dev | Starter app på `localhost` med default testdata
| npm run dev -- <filnavn> | Starter app på `localhost` med angitt testdata
| npm run test | Kjører alle tester
| npm run build | Bygger applikasjonen klar til produksjon til `build`-mappa. Bygger også dokumentasjonen som vil bli tilgjengelig på `/pensjon/opptjening/doc`
|===

== Lokal backend konfigurasjon
Applikasjonen vil default kjøre opp en lokal JSON-server for mockede data.
JSON-server kjører på port 4000, og det blir satt opp en proxy som endre kall til backend til å kalle den lokale serveren.

Ønsker man å kjøre opp den ekte backend serveren lokalt, så kan man endre i filen `setupProxy.js` til å gå til denne istedet.

