FROM nginxinc/nginx-unprivileged:stable-alpine3.23-slim

USER root
RUN apk update && apk upgrade --no-cache libssl3 libcrypto3
USER nginx

COPY /build /usr/share/nginx/html

# Will extract environment variables before nginx starts (ref. https://hub.docker.com/_/nginx):
COPY .nginx/gcp.conf /etc/nginx/templates/default.conf.template
