apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-selvbetjening-opptjening-frontend
  namespace: pensjonselvbetjening
  labels:
    team: pensjonselvbetjening
  annotations:
    nais.io/run-as-user: "101" # nginx
    nais.io/read-only-file-system: "false" # need write /etc/nginx/conf.d
spec:
  image: {{ image_prod_gcp }}
  port: 8080
  replicas:
    min: 2
    max: 2
  liveness:
    path: "/api/internal/isAlive"
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  readiness:
    path: "/api/internal/isReady"
    initialDelay: 30
    timeout: 1
  accessPolicy:
    outbound:
      rules:
        - application: pensjon-selvbetjening-opptjening-backend
          cluster: prod-fss
  ingresses:
    - "https://pensjon-selvbetjening-opptjening-frontend.intern.nav.no"
    - "https://www.nav.no/pensjon/opptjening"
  env:
    - name: "OPPTJENING_BACKEND"
      value: "https://pensjon-selvbetjening-opptjening-backend.prod-fss-pub.nais.io"
