name: Cypress end-to-end tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.33.0

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: pnpm

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: /home/runner/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-

      - name: Install dependencies and verify Cypress
        # print Cypress and OS info
        run: |
          pnpm install --frozen-lockfile
          pnpm exec cypress install
          pnpm exec cypress verify
          pnpm exec cypress info
          pnpm exec cypress version
          pnpm exec cypress version --component package
          pnpm exec cypress version --component binary
          pnpm exec cypress version --component electron
          pnpm exec cypress version --component node
      - name: Run build
        run: pnpm build:cypress
      - name: Cypress run with express.js
        run: pnpm test:cycli #172.17.0.1 = docker.internal.host on linux
        env:
          HOST: "172.17.0.1"
      - name: Upload screenshots if Cypress tests failed
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: |
            e2e/cypress/screenshots
            e2e/cypress/logs
            e2e/cypress/snapshots
            cypress/screenshots
            cypress/logs
            cypress/snapshots
