name: Deploy to dev-gcp

on: workflow_dispatch

jobs:
  deploy-to-dev:
    name: Deploy to dev-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      IMAGE_DEV_GCP: ghcr.io/${{ github.repository }}/pensjon-selvbetjening-opptjening-frontend-dev-gcp:${{ github.sha }}
    steps:
      - name: Use Node.js v12.18.3
        uses: actions/setup-node@v1
        with:
          node-version: "12.18.3"
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --watchAll=false
      - name: Build application
        env:
          REACT_APP_LOGINSERVICE_URL: "not used in GCP"
          REACT_APP_OPPTJENING_ENDPOINT: "/api/opptjening"
          REACT_APP_DECORATOR_URL: "https://dekoratoren.dev.nav.no"
          REACT_APP_DINPENSJON_URL: "https://pensjon-pselv-q2-gcp.dev.nav.no/pselv/publisering/dinpensjon.jsf"
          REACT_APP_PENSJONSKALKULATOR_URL: "https://pensjon-pselv-q2-gcp.dev.nav.no/pselv/simulering.jsf"
          REACT_APP_OVERFORE_OMSORGSOPPTJENING_URL: "https://pensjon-pselv-q2-gcp.dev.nav.no/pselv/publisering/overforeomsorgspoeng.jsf"
        run: npm run build
      - name: Build Docker image dev-gcp
        run: |
          docker build -f .docker/Dockerfile-gcp -t ${IMAGE_DEV_GCP} .
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/Dockerfile-gcp
          push: true
          tags: ${{ env.IMAGE_DEV_GCP }}
      - name: Generate NAIS variables dev-gcp
        run: |
          cat > .nais/vars-dev-gcp.yaml <<EOF
          namespace: pensjonselvbetjening
          image_dev_gcp: $IMAGE_DEV_GCP
          EOF
      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev-gcp.yml
          VARS: .nais/vars-dev-gcp.yaml
