name: Deploy dev-gcp internal version

on: workflow_dispatch

jobs:
  deploy-to-dev:
    name: Deploy internal to dev-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Use Node.js v12.18.3
        uses: actions/setup-node@v1
        with:
          node-version: "12.18.3"
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --watchAll=false
      - name: Build application
        env:
          REACT_APP_LOGINSERVICE_URL: "https://pensjon-veiledning-opptjening-frontend.intern.dev.nav.no/pensjon/opptjening/oauth2/internal/login?redirect="
          REACT_APP_OPPTJENING_ENDPOINT: "/api/opptjeningonbehalf"
          REACT_APP_DECORATOR_URL: "https://dekoratoren.ekstern.dev.nav.no"
          REACT_APP_DINPENSJON_URL: "https://pensjon-selvbetjening-dinpensjon-frontend-veileder-q2.ansatt.dev.nav.no/pensjon/selvbetjening/dinpensjon"
          REACT_APP_PENSJONSKALKULATOR_URL: "https://pensjonskalkulator-veiledning-frontend-staging.ansatt.dev.nav.no/pensjon/kalkulator"
          REACT_APP_OVERFORE_OMSORGSOPPTJENING_URL: "https://opptjening-overforomsorgsopptjening-frontend-veileder-q2.intern.dev.nav.no/pensjon/selvbetjening/overforomsorgsopptjening"
          REACT_APP_REPRESENTASJON_BANNER: "https://representasjon-banner-frontend-borger-q2.intern.dev.nav.no/pensjon/selvbetjening/representasjon"
        run: npm run build
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          image_suffix: intern-dev
          team: pensjonselvbetjening
          dockerfile: .docker/Dockerfile-gcp-intern
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Deploy internal to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          IMAGE: ${{ steps.docker-push.outputs.image }}
          CLUSTER: dev-gcp
          VARS: .nais/vars-dev-gcp-intern.yaml
