name: Deploy to dev-gcp

on: workflow_dispatch

jobs:
  deploy-to-dev:
    name: Deploy to dev-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://npm.pkg.github.com"
          cache: npm
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --watchAll=false
      - name: Build application
        env:
          REACT_APP_LOGINSERVICE_URL: "not used in GCP"
          REACT_APP_OPPTJENING_ENDPOINT: "/api/opptjening"
          REACT_APP_DECORATOR_URL: "https://dekoratoren.ekstern.dev.nav.no"
          REACT_APP_DINPENSJON_URL: "https://pensjon-selvbetjening-dinpensjon-frontend-borger-q2.ansatt.dev.nav.no/pensjon/selvbetjening/dinpensjon"
          REACT_APP_PENSJONSKALKULATOR_URL: "https://staging.ekstern.dev.nav.no/pensjon/kalkulator"
          REACT_APP_OVERFORE_OMSORGSOPPTJENING_URL: "https://opptjening-overforomsorgsopptjening-frontend-borger-q2.intern.dev.nav.no/pensjon/selvbetjening/overforomsorgsopptjening/"
          REACT_APP_REPRESENTASJON_BANNER: "https://representasjon-banner-frontend-borger-q2.intern.dev.nav.no/pensjon/selvbetjening/representasjon"
        run: npm run build
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          image_suffix: external-dev
          team: pensjonselvbetjening
          dockerfile: .docker/Dockerfile
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Deploy
        uses: nais/deploy/actions/deploy@v2
        env:
          IMAGE: ${{ steps.docker-push.outputs.image }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev-gcp.yml,.nais/unleash-dev.yml
