name: NAIS Deploy to dev-fss

on: workflow_dispatch

jobs:
  deploy-to-dev:
    name: Deploy to dev-fss
    runs-on: ubuntu-latest
    env:
      IMAGE_DEV_FSS: ghcr.io/${{ github.repository }}/pensjon-selvbetjening-opptjening-frontend-dev-fss:${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --watchAll=false
      - name: Build application
        env:
          REACT_APP_LOGINSERVICE_URL: "https://pensjon-selvbetjening-opptjening-frontend.dev.adeo.no/pensjon/opptjening/oauth2/internal/login?redirect="
          REACT_APP_OPPTJENING_ENDPOINT: "/api/opptjeningonbehalf"
          REACT_APP_DECORATOR_URL: "https://static-v4-decorator.nais.adeo.no"
          REACT_APP_DINPENSJON_URL: "https://pensjon-pselv-q2.dev.adeo.no/pselv/publisering/dinpensjon.jsf"
          REACT_APP_DINEPENSJONSPOENG_URL: "https://pensjon-pselv-q2.dev.adeo.no/pselv/publisering/dinepensjonspoeng.jsf"
          REACT_APP_PENSJONSKALKULATOR_URL: "https://pensjon-pselv-q2.dev.adeo.no/pselv/simulering.jsf"
          REACT_APP_OVERFORE_OMSORGSOPPTJENING_URL: "https://pensjon-pselv-q2.dev.adeo.no/pselv/publisering/overforeomsorgspoeng.jsf"
        run: npm run build
      - name: Build Docker image dev-fss
        run: |
          docker build -f Dockerfile-fss -t ${IMAGE_DEV_FSS} .
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-fss
          push: true
          tags: ${{ env.IMAGE_DEV_FSS }}
      - name: Generate NAIS variables dev-fss
        run: |
          cat > .nais/vars-dev-fss.yaml <<EOF
          namespace: pensjonselvbetjening
          image_dev_fss: $IMAGE_DEV_FSS
          EOF
      - name: Deploy to dev-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: .nais/dev-fss.yml
          VARS: .nais/vars-dev-fss.yaml
