name: Test code

on: [push]

jobs:
  run-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: pnpm
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.33.0
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm exec cypress verify
          pnpm exec cypress info
          pnpm exec cypress version
          pnpm exec cypress version --component package
      - name: Run tests
        run: pnpm test -- --watchAll=false
